MCP Manager: frontend/src/services/events.ts File Reference
events.ts File Reference
Functions
function export setupWailsEvents ()
Initialize Wails event listeners.
function export cleanupWailsEvents ()
Clean up Wails event listeners.
function handleServerDiscovered (data:any)
Handle server discovered event.
function async handleServerStatusChanged (data:any)
Handle server status changed event.
function handleServerLogEntry (data:any)
Handle server log entry event.
function handleServerMetricsUpdated (data:any)
Handle server metrics updated event.
function handleServerConfigUpdated (data:any)
Handle server config updated event FR-050: Notify user of external config changes and prompt to refresh.
function handleServersUpdate (servers:MCPServer[], actionType:string)
Handle servers update (initial load or discovery) Issue 2 fix: Update servers store when discovery completes.
Variables
import { EventsOn, EventsOff } from '../../wailsjs/runtime/runtime'
export type WailsEventType
Function Documentation
cleanupWailsEvents()
function export cleanupWailsEvents ()
Clean up Wails event listeners.
Definition at line 76 of file events.ts.
handleServerConfigUpdated()
function handleServerConfigUpdated (data:any)
Handle server config updated event FR-050: Notify user of external config changes and prompt to refresh.
Definition at line 172 of file events.ts.
References addNotification(), any, and data.
Referenced by setupWailsEvents().
handleServerDiscovered()
function handleServerDiscovered (data:any)
Handle server discovered event.
Definition at line 90 of file events.ts.
References addNotification(), any, and data.
Referenced by setupWailsEvents().
handleServerLogEntry()
function handleServerLogEntry (data:any)
Handle server log entry event.
Definition at line 135 of file events.ts.
References addLog(), addNotification(), any, data, and LogEntry.
Referenced by setupWailsEvents().
handleServerMetricsUpdated()
function handleServerMetricsUpdated (data:any)
Handle server metrics updated event.
Definition at line 158 of file events.ts.
References any, data, ServerMetrics, and updateMetrics().
Referenced by setupWailsEvents().
handleServerStatusChanged()
function async handleServerStatusChanged (data:any)
Handle server status changed event.
Definition at line 101 of file events.ts.
References addNotification(), any, data, error, and updateServer().
Referenced by setupWailsEvents().
handleServersUpdate()
function handleServersUpdate (servers:MCPServer[], actionType:string)
Handle servers update (initial load or discovery) Issue 2 fix: Update servers store when discovery completes.
Definition at line 185 of file events.ts.
References addNotification(), data, MCPServer, and servers.
Referenced by setupWailsEvents().
setupWailsEvents()
function export setupWailsEvents ()
Initialize Wails event listeners.
Definition at line 27 of file events.ts.
References any, data, handleServerConfigUpdated(), handleServerDiscovered(), handleServerLogEntry(), handleServerMetricsUpdated(), handleServerStatusChanged(), handleServersUpdate(), MCPServer, and servers.
Variable Documentation
import
import { EventsOn, EventsOff } from '../../wailsjs/runtime/runtime'
Definition at line 1 of file events.ts.
WailsEventType
export type WailsEventType
Initial value:
=
  | 'server:discovered'
  | 'server:status:changed'
  | 'server:log:entry'
  | 'server:config:updated'
  | 'server:metrics:updated'
  | 'servers:initial'
  | 'servers:discovered'
Definition at line 15 of file events.ts.