// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerToClientConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddServerToClientConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function DetectClients() {
  return window['go']['main']['App']['DetectClients']();
}

export function DiscoverServers() {
  return window['go']['main']['App']['DiscoverServers']();
}

export function GetAllLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllLogs'](arg1, arg2, arg3, arg4);
}

export function GetApplicationState() {
  return window['go']['main']['App']['GetApplicationState']();
}

export function GetConfiguration(arg1) {
  return window['go']['main']['App']['GetConfiguration'](arg1);
}

export function GetDependencies(arg1) {
  return window['go']['main']['App']['GetDependencies'](arg1);
}

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetMetrics(arg1) {
  return window['go']['main']['App']['GetMetrics'](arg1);
}

export function GetNetstat(arg1) {
  return window['go']['main']['App']['GetNetstat'](arg1);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetUpdates(arg1) {
  return window['go']['main']['App']['GetUpdates'](arg1);
}

export function LaunchShell() {
  return window['go']['main']['App']['LaunchShell']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function OpenExplorer(arg1) {
  return window['go']['main']['App']['OpenExplorer'](arg1);
}

export function ReadClientConfig(arg1) {
  return window['go']['main']['App']['ReadClientConfig'](arg1);
}

export function RemoveServerFromClientConfig(arg1, arg2) {
  return window['go']['main']['App']['RemoveServerFromClientConfig'](arg1, arg2);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StopServer'](arg1, arg2, arg3);
}

export function UpdateApplicationState(arg1) {
  return window['go']['main']['App']['UpdateApplicationState'](arg1);
}

export function UpdateConfiguration(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfiguration'](arg1, arg2);
}

export function WriteClientConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteClientConfig'](arg1, arg2);
}

export function GetNetstat(arg1) {
  return window['go']['main']['App']['GetNetstat'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}
