// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {models} from '../models';
import {dependencies} from '../models';

export function AddServerToClientConfig(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Record<string, string>):Promise<void>;

export function DetectClients():Promise<Array<config.ClientInfo>>;

export function DiscoverServers():Promise<main.DiscoverServersResponse>;

export function GetAllLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.GetLogsResponse>;

export function GetApplicationState():Promise<models.ApplicationState>;

export function GetConfiguration(arg1:string):Promise<models.ServerConfiguration>;

export function GetDependencies(arg1:string):Promise<main.GetDependenciesResponse>;

export function GetLogs(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.GetLogsResponse>;

export function GetMetrics(arg1:string):Promise<models.ServerMetrics>;

export function GetNetstat(arg1:Array<number>):Promise<main.NetstatResponse>;

export function GetServer(arg1:string):Promise<models.MCPServer>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetServices():Promise<main.ServicesResponse>;

export function GetUpdates(arg1:string):Promise<dependencies.UpdateInfo>;

export function LaunchShell():Promise<main.LaunchShellResponse>;

export function ListServers():Promise<main.ListServersResponse>;

export function OpenExplorer(arg1:string):Promise<main.OpenExplorerResponse>;

export function ReadClientConfig(arg1:string):Promise<config.ClientConfig>;

export function RemoveServerFromClientConfig(arg1:string,arg2:string):Promise<void>;

export function RestartServer(arg1:string):Promise<main.ServerOperationResponse>;

export function StartServer(arg1:string):Promise<main.ServerOperationResponse>;

export function StopServer(arg1:string,arg2:boolean,arg3:number):Promise<main.ServerOperationResponse>;

export function UpdateApplicationState(arg1:models.ApplicationState):Promise<main.UpdateApplicationStateResponse>;

export function UpdateConfiguration(arg1:string,arg2:models.ServerConfiguration):Promise<models.ServerConfiguration>;

export function WriteClientConfig(arg1:string,arg2:config.ClientConfig):Promise<void>;
